USE [master]
GO

/****** Object:  Database [northwind]    Script Date: 1/15/2014 11:47:42 AM ******/
CREATE DATABASE [northwind]

 /*CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Northwind', FILENAME = N'D:\2\NORTHWND.MDF' , SIZE = 4992KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Northwind_log', FILENAME = N'D:\2\northwind_log.ldf' , SIZE = 3456KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
*/

GO

ALTER DATABASE [northwind] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [northwind].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [northwind] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [northwind] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [northwind] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [northwind] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [northwind] SET ARITHABORT OFF 
GO

ALTER DATABASE [northwind] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [northwind] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [northwind] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [northwind] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [northwind] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [northwind] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [northwind] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [northwind] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [northwind] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [northwind] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [northwind] SET  DISABLE_BROKER 
GO

ALTER DATABASE [northwind] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [northwind] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [northwind] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [northwind] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [northwind] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [northwind] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [northwind] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [northwind] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [northwind] SET  MULTI_USER 
GO

ALTER DATABASE [northwind] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [northwind] SET DB_CHAINING OFF 
GO

ALTER DATABASE [northwind] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [northwind] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [northwind] SET  READ_WRITE 
GO


